spring:
  application:
    name: payment
  server:
    port: "${SERVER_PORT:8080}"
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: "${POSTGRES_URL}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
lncr:
  internalUrl: "${LNCR_INTERNAL_URL:http://localhost:8080}"
  externalUrl: "${LNCR_EXTERNAL_URL::http://localhost:8080}"
  integration:
    customerOrdersUrl: "${lncr.internalUrl}/customerOrders"
    paymentsUrl: "${lncr.internalUrl}/payments/mercadoPago"
    notificationUrl: "${lncr.internalUrl}/notifications"
  mercadopago:
    locationPrefix: "${lncr.externalUrl}/payments/mercadoPago"
    oauthUrl: "${MERCADOPAGO_OAUTH_URL}"
    ordersUrl: "${MERCADOPAGO_ORDERS_URL}"
    clientId: "${MERCADOPAGO_CLIENT_ID}"
    secretId: "${MERCADOPAGO_SECRET_ID}"#.env
    posId: "${MERCADOPAGO_POS_ID}" #.env
    expirationTime: "${MERCADOPAGO_EXPIRATION_TIME}" # 1 hora
    webhookSecret: "${MERCADOPAGO_WEBHOOK_SECRET}"
    webhookValidationSignature: "${MERCADOPAGO_WEBHOOK_VALIDATION_SIGNATURE:true}" #Para validação local quando não se tem o valor da assinatura