spring:
  application:
    name: lncr-ms-payment
  server:
    port: "${SERVER_PORT:8080}"
  datasource:
    url: "${POSTGRES_URL}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
lncr:
  internalUrl: "${LNCR_ALB_URL:http://localhost:8080}"
  externalUrl: "${LNCR_EXTERNAL_URL}"
  integration:
    customersUrl: "${lncr.internalUrl}/customers"
    customerOrdersUrl: "${lncr.internalUrl}/customerOrders"
    foodItemsUrl: "${lncr.internalUrl}/foodItems"
    kitchenOrdersUrl: "${lncr.internalUrl}/kitchenOrders"
    paymentsUrl: "${lncr.internalUrl}/payments"
    notificationUrl: "${lncr.internalUrl}/notifications"

  mercadopago:
    locationPrefix: "${lncr.externalUrl}/payments/mercadoPago"
    oauthUrl: "${MERCADOPAGO_OAUTH_URL}"
    ordersUrl: "${MERCADOPAGO_ORDERS_URL}"
    clientId: "${MERCADOPAGO_CLIENT_ID}"
    secretId: "${MERCADOPAGO_SECRET_ID}"#.env
    posId: "${MERCADOPAGO_POS_ID}" #.env
    expirationTime: "${MERCADOPAGO_EXPIRATION_TIME}" # 1 hora
    webhookSecret: "${MERCADOPAGO_WEBHOOK_SECRET}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always


