apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  
  labels:
    app: {{ .Values.app.name }}
data:
  LNCR_INTERNAL_URL: {{ .Values.app.internalUrl | quote }}
  LNCR_EXTERNAL_URL: {{ .Values.app.externalUrl | quote }}
  MERCADOPAGO_OAUTH_URL: {{ .Values.app.mercadoPago.oauthUrl | quote }}
  MERCADOPAGO_ORDERS_URL: {{ .Values.app.mercadoPago.ordersUrl | quote }}
  MERCADOPAGO_EXPIRATION_TIME: {{ .Values.app.mercadoPago.expirationTime | quote }}

