{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  labels:
    app: {{ .Values.app.name }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "alb" }}
  rules:
  {{- range .Values.ingress.hosts }}
  - {{- if .host }}
    host: {{ .host | quote }}
    {{- end }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.app.name }}-service
            port:
              number: {{ $.Values.service.port }}
      {{- end }}
  {{- end }}
{{- end -}}
