apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  
  labels:
    app: {{ .Values.app.name }}
data:
  LNCR_INTERNAL_URL: {{ .Values.app.internalUrl | quote }}
  LNCR_EXTERNAL_URL: {{ .Values.app.externalUrl | quote }}
  MERCADOPAGO_OAUTH_URL: {{ .Values.app.mercadoPago.oauthUrl | quote }}
  MERCADOPAGO_ORDERS_URL: {{ .Values.app.mercadoPago.ordersUrl | quote }}
  MERCADOPAGO_EXPIRATION_TIME: {{ .Values.app.mercadoPago.expirationTime | quote }}
  MERCADOPAGO_WEBHOOK_VALIDATION_SIGNATURE: {{ .Values.app.mercadoPago.webhookValidationSignature | quote }}
  JAVA_TOOL_OPTIONS: >-
    -XX:+UseContainerSupport
    -XX:MaxRAMPercentage=75.0
    -XX:InitialRAMPercentage=50.0
    -XX:+UseG1GC
    -XX:MaxGCPauseMillis=100
    -XX:+UseStringDeduplication
    -Xss256k
    -XX:ReservedCodeCacheSize=64m
    -Djava.security.egd=file:/dev/./urandom

