apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name | default "default-secret-provider-class" }}
  namespace: {{ .Values.secretProviderClass.namespace | default "default" }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  provider: {{ .Values.secretProviderClass.provider | default "aws" | quote }}
  parameters:
    region: {{ .Values.secretProviderClass.parameters.region | quote }}
    {{- if and .Values.secretProviderClass.twoSecrets .Values.secretProviderClass.twoSecrets.enabled }}
    objects: |
{{- .Values.secretProviderClass.parameters.objects | nindent 6 }}
    {{- else }}
    objects: |
      - objectName: {{ index .Values.secretProviderClass.parameters.objects 0 "objectName" | quote }}
        objectType: {{ index .Values.secretProviderClass.parameters.objects 0 "objectType" | quote }}
        jmesPath:
          {{- range .Values.secretProviderClass.keys }}
          - path: "{{ . }}"
            objectAlias: "{{ . }}"
          {{- end }}
    {{- end }}
  secretObjects:
    {{- range .Values.secretProviderClass.secretObjects }}
    - secretName: {{ .secretName | quote }}
      type: {{ .type | quote }}
      data:
        {{- if and $.Values.secretProviderClass.twoSecrets $.Values.secretProviderClass.twoSecrets.enabled }}
        {{- range $.Values.secretProviderClass.twoSecrets.keys }}
        - key: "{{ . }}"
          objectName: "{{ . }}"
        {{- end }}
        {{- else }}
        {{- range $.Values.secretProviderClass.keys }}
        - key: "{{ . }}"
          objectName: "{{ . }}"
        {{- end }}
        {{- end }}
    {{- end }}